# Generated by Django 5.1.3 on 2024-12-11 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.university')),
                ('quota_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.quotatype')),
                ('scholarship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scholarshiptype')),
                ('score_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scoretype')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.year')),
            ],
        ),
    ]
